name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setuo Docker Build
      uses: docker/setup-buildx-action@v3.6.1
